words = [
    "autolinks",
    "breakpoint",
    "buftypes",
    "concealcursor",
    "conceallevel",
    "dla",
    "dlv",
    "inlines",
    "lazygit",
    "linewise",
    "markview",
    "neovim's",
    "nvim",
    "pynvim",
    "renderers",
    "rtp",
    "statusline",
    "virt",
]
