words = [
    "autocmds",
    "autolinks",
    "breakpoint",
    "bufnr",
    "buftypes",
    "concealcursor",
    "conceallevel",
    "dla",
    "dlv",
    "extmark",
    "inlines",
    "lazygit",
    "linewise",
    "markview",
    "neovim",
    "neovim's",
    "nvim",
    "pynvim",
    "renderers",
    "rtp",
    "statusline",
    "virt",
]
