return {
  cmd          = { 'gopls' },
  filetypes    = { 'go', 'gomod', 'gowork', 'gotmpl' },
  root_markers = { 'go.work', 'go.mod', '.git' },
  settings = {
    gopls = {
      gofumpt = true,
      symbolStyle = 'Dynamic',
      buildFlags = { '-tags=integration,unit,test,pact,release,mock' },
      vulncheck = 'Imports',
      standaloneTags = { 'ignore', 'mage' },
      usePlaceholders = true,
      completeUnimported = true,
      directoryFlags = { '-.git', '-.vscode', '-.idea', '-.vscode-test', '-node_modules' },
      completeFunctionCalls = true,
      linksInHover = true,
      staticcheck = true,
      codelenses = {
        gc_details = true,
        generate = true,
        regenerate_cgo = true,
        run_govulncheck = true,
        test = true,
        tidy = true,
        upgrade_dependency = true,
        vendor = true,
      },
      hints = {
        assignVariableTypes = true,
        compositeLiteralFields = true,
        compositeLiteralTypes = true,
        constantValues = true,
        functionTypeParameters = true,
        parameterNames = true,
        rangeVariableTypes = true,
      },
      analyses = {
        nilness = true,
        unusedparams = true,
        unusedwrite = true,
        useany = true,
      },
      ui = {
        semanticTokens = true,
      },
    },
  },
}
