---@module "lspconfig"
---@type vim.lsp.Config
return {
  cmd = { "gopls" },
  filetypes = { "go", "gomod", "gowork", "gotmpl" },
  root_markers = { "go.work", "go.mod" },
  single_file_support = true,
  settings = {
    gopls = {
      gofumpt = true,
      symbolStyle = "Dynamic",
      buildFlags = {},
      diagnosticsDelay = "750ms",
      directoryFilters = {
        "-.git",
        "-node_modules",
        "-vendor",
        "-tmp",
        "-dist",
      },
      vulncheck = "Off",
      standaloneTags = { "ignore", "mage" },
      usePlaceholders = true,
      completeUnimported = true,
      completeFunctionCalls = true,
      linksInHover = true,
      staticcheck = false,
      codelenses = {
        gc_details = false,
        generate = true,
        regenerate_cgo = false,
        run_govulncheck = false,
        test = true,
        tidy = false,
        upgrade_dependency = false,
        vendor = false,
      },
      hints = {
        assignVariableTypes = false,
        compositeLiteralFields = true,
        compositeLiteralTypes = false,
        constantValues = false,
        functionTypeParameters = false,
        parameterNames = true,
        rangeVariableTypes = false,
      },
      analyses = {
        nilness = true,
        unusedparams = false,
        unusedwrite = false,
        useany = false,
      },
    },
  },
}
